name: My Composite Action
description: A composite action that does something
outputs:
  result:
    description: 'The result of the composite action'
    value: ${{ steps.task.output.result }}
runs:
  using: "composite"
  steps:
    - name: Perform some task
      id: task
      shell: bash
      run: |
        result=$(echo "Hello, World!")
        echo "result=$result" >> $GITHUB_OUTPUT


