name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  job1:
    runs-on: [self-hosted, linux, ARM64]
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: [self-hosted, linux, ARM64]
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: print-something
        env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            OUTPUT2: ${{needs.job1.outputs.output2}}
        run: |
            echo "$OUTPUT1 $OUTPUT2"
            cat ./variables.env >> $GITHUB_ENV
            echo "ISTIO_VAULT_SIGNIN_SECRET_ID_B64=secret-id-64" >> $GITHUB_ENV
            echo "ISTIO_VAULT_SIGNIN_ROLE_ID:role-id"  >> $GITHUB_ENV

          
