name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      structs:
        description: 'List of structs in JSON format'
        required: true
        default: |
          [
            {
              "name": "Alice \"The Great\"",
              "age": 30
            },
            {
              "name": "Bob",
              "age": 25
            }
          ]

jobs:
  prepare-matrix:
    runs-on: ubuntu-lastest
    outputs:
      my-matrix: ${{ steps.set-matrix.outputs.my-matrix }}
    steps:
      - name: Set matrix from structs
        id: set-matrix
        run: |
          echo "Parsing structs input..."
          echo '${{ github.event.inputs.structs }}' | jq -c '.' > structs.json
          MATRIX=$(cat structs.json)
          printf 'my-matrix=%s\n' "${MATRIX}" >> $GITHUB_OUTPUT

  run-jobs:
    needs: prepare-matrix
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        struct: ${{ fromJson(needs.prepare-matrix.outputs.my-matrix) }}
    steps:
      - name: Run job for each entry
        run: |
          echo "Running job for name: ${{ matrix.struct.name }} and age: ${{ matrix.struct.age }}"
          # Your actual job logic here
          echo "Name: ${{ matrix.struct.name }}, Age: ${{ matrix.struct.age }}"
