name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      structs:
        description: 'List of structs in JSON format'
        required: true
        default: '[{"name": "Alice", "age": 30}, {"name": "Bob", "age": 25}]'

jobs:
  prepare-matrix:
    runs-on: [self-hosted, linux, ARM64]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix from structs
        id: set-matrix
        run: |
          echo "Parsing structs input..."
          echo '${{ github.event.inputs.structs }}' | jq -c '.' > structs.json
          MATRIX=$(cat structs.json)
          printf 'matrix=%s\n' "${MATRIX}" >> $GITHUB_OUTPUT

  run-jobs:
    needs: prepare-matrix
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      matrix:
        struct: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Run job for each entry
        run: |
          echo "Running job for name: ${{ matrix.struct.name }} and age: ${{ matrix.struct.age }}"
          # Your actual job logic here
          echo "Name: ${{ matrix.struct.name }}, Age: ${{ matrix.struct.age }}"
