name: Test matrix with input

on: 
  workflow_dispatch:
    inputs:
      cluster-metadata:  
        description: 'List of structs in JSON format'
        required: true
        default: |
          [
            {
              "cluster-name": "cluster-eks-dev-default",
              "env-file": ".github/variables/dev.env"
            },
            {
              "cluster-name": "cluster-eks-dev-aut",
              "env-file": ".github/variables/dev-aut.env"
            }
          ]

jobs:
  process-input:
    runs-on: [self-hosted, linux, ARM64]
    strategy:
        matrix: ${{ fromJSON(inputs.cluster-metadata) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Populate cluster local variables
        run: |
          cat ${{ matrix.env-file }} >> $GITHUB_ENV
