name: Main Secrets flow
on:
  workflow_dispatch:

jobs:
    setup-mesh:
      uses: sakhdlam/istio/.github/workflows/reusable-workflow.yaml@main
      with:
        config-path: .github/labeler.yml
      secrets:
        envPAT: "some-id-sakhie"
