name: Matrix Build and Collect Results

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        id: run_script
        run: |
          echo "Running on OS: ${{ matrix.os }} and Node.js: ${{ matrix.node }}"
          # Simulating a result based on the matrix combination
          RESULT="${{ matrix.os }}-${{ matrix.node }}-result"
          echo "::set-output name=result::$RESULT"

      - name: Set output
        id: set_output
        run: echo "result=${{ steps.run_script.outputs.result }}" >> $GITHUB_ENV

  collect-results:
    needs: build
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Collect results
        run: |
          echo "Results from matrix build:"
          echo "${{ needs.build.outputs.result }}"
          # for os in ubuntu-latest macos-latest windows-latest; do
          #   for node in 12 14 16; do
          #     job_output=$(echo "${{ needs.build.outputs.result }}" | grep "${os}-${node}")
          #     echo "Result for OS $os and Node.js $node: $job_output"
          #   done
          # done
