name: Matrix Build and Collect Results

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        id: run_script
        run: |
          echo "Running on OS: ${{ matrix.os }} and Node.js: ${{ matrix.node }}"
          # Simulating a result based on the matrix combination
          RESULT="${{ matrix.os }}-${{ matrix.node }}-result"
          echo "RESULT=$RESULT" >> $GITHUB_ENV
          echo $RESULT > result.txt

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: result-${{ matrix.os }}-${{ matrix.node }}
          path: result.txt

  collect-results:
    needs: build
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download results
        uses: actions/download-artifact@v2
        with:
          path: results/

      - name: Print results
        run: |
          echo "Results from matrix build:"
          for file in results/*; do
            find . -type f -print -exec cat {} \
          done
