name: Istio mesh Setup
on:
  workflow_call:
    inputs:
      cluster-metadata:
        type: string
        description: cluster-metadata

jobs:
  setup-pki:
    runs-on:  [self-hosted, linux, ARM64]
    steps:
       # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v2
      - name: Setup mesh
        uses: sakhdlam/istio@main
        with:
          cluster-metadata: ${{ inputs.cluster-metadata }}
