name: Istio mesh Setup
on:
  workflow_call:
    inputs:
      cluster-metadata:
        type: string
        description: cluster-metadata

jobs:
  setup-pki:
    runs-on:  [self-hosted, linux, ARM64]
    steps:
       # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v2
      - name: Checkout local vars
        shell: bash
        run: cat ./variables.env >> $GITHUB_ENV
      - name: Setup mesh
        uses: sakhdlam/istio@main
        env:
          ISTIO_VAULT_SIGNIN_SECRET_ID_B64: "secret-id-64"
          ISTIO_VAULT_SIGNIN_ROLE_ID: "role-id"
          ISTIO_VAULT_PKI_CERT_SIGN_ROLE: "cert-sign-role"
        with:
          cluster-metadata: ${{ inputs.cluster-metadata }}
