name: Another Example Workflow

on: 
    workflow_dispatch:
      inputs:
        structs:  
          description: 'List of structs in JSON format'
          required: true
          default: |
            [
              {
                "name": "Alice \"The Great\"",
                "age": 30
              },
              {
                "name": "Bob",
                "age": 25
              }
            ]

jobs:
  process-json:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Capture cluster-metadata
      run: echo "CLUSTER_METADATA=${{ inputs.cluster-metadata }}" >> $GITHUB_ENV

    - name: Run script
      shell: bash
      run: |
        # Ensure the environment variable is properly assigned
        cluster_metadata="$CLUSTER_METADATA"
        
        # Print the received metadata for verification
        echo "$cluster_metadata"
        
        # You can now use the JSON string in your script
        # For example, you could parse it with jq if needed
        echo "$cluster_metadata" | jq '.'
