name: Another Example Workflow

on: 
    workflow_dispatch:
      inputs:
        structs:  
          description: 'List of structs in JSON format'
          required: true
          default: |
            [
              {
                "name": "Alice \"The Great\"",
                "age": 30
              },
              {
                "name": "Bob",
                "age": 25
              }
            ]

jobs:
  process-json:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Capture cluster-metadata
      run: echo "CLUSTER_METADATA=${{ inputs.cluster-metadata }}" >> $GITHUB_ENV

    - name: Run script
      run: ./test.sh
