name: Workflow Using Composite Action
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run composite action
        id: mycomposite
        uses: sakhdlam/istio@main

      - name: Set output for next job
        run: echo "result=${{ steps.mycomposite.outputs.result }}" >> $GITHUB_ENV

  job2:
    runs-on: [self-hosted, linux, ARM64]
    needs: job1

    steps:
      - name: Use composite action output
        run: echo "The result is ${{ needs.job1.outputs.result }}"
