on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: [self-hosted, linux, ARM64]
    environment: production
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.envPAT }}
          configuration-path: ${{ inputs.config-path }}
      - name: Install istio
        uses: sakhdlam/istio@main
         
