name: CI Pipeline

on: [push]

jobs:
  save-secrets:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "AWS_ACCESS_KEY_ID="sakhile-percy" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY="Dlamini-nkhosi" >> $GITHUB_ENV

    - name: Save secrets to a file
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > secrets.env
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> secrets.env

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: secrets
        path: secrets.env

  use-secrets:
    needs: save-secrets
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: secrets
        path: .

    - name: Load secrets
      run: |
        source secrets.env
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

    - name: Use secrets
      run: |
        echo "AWS_ACCESS_KEY_ID is $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY is $AWS_SECRET_ACCESS_KEY"
